name: 'Wrap release in folder'
on:
  release:
    types: [published]

jobs:
  wrap-release:
    runs-on: ubuntu-latest
    steps:
      # Check the code
      - name: Checkout repo
        uses: actions/checkout@v4.2.1

      # Update the plugin.json with tag version
      - name: Add tag version to plugin.json
        run: |
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${GITHUB_REF#v}\"/" plugin.json

      # Create a folder and move the files inside
      - name: Create folder and move files
        run: |
          mkdir configgenerator
          mv * configgenerator || true

      # Create a zip of the folder
      - name: Create ZIP file
        run: zip -r configgenerator.zip configgenerator

      # Upload the zip file
      - name: Upload the zip file
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./configgenerator.zip"]'
