name: "Wrap release in folder"
on: 
  release:
    types: [published]

jobs:
  wrap-release:
    runs-on: ubuntu-latest
    steps:
      # Check the code
      - name: Checkout repo
        uses: actions/checkout@v4.2.1

      # Create a folder and move the files inside
      - name: Create folder and move files
        run: |
          mkdir release-folder
          mv * release-folder || true # Move all files into the folder
          mv .[^.]* release-folder || true # Move dotfiles (like .gitignore) to the folder

      # Create a zip of the folder
      - name: Create ZIP file
        run: zip -r newasset.zip release-folder

      - name: Release Asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./newasset.zip"]'
